# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ctypes import addressof
from sys import stdout
from typing import Counter
from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess
from subprocess import Popen, PIPE
import json
import requests
import threading


def connectIface_function():
        # global p 
        # if (p =='None'):
        #     urn = "java -jar leshan-client-demo.jar "+ "-n "+ "urn:lo:lwm2m:"+ self.connectClient_inputEndPointName.text() +" -i "+ self.connectClient_inputEndPointName.text()+" -p 1d576207727841a7b9aa2a1f24448f86 -u lwm2m.integ.m2m.orange.com"
        #     urn = urn.strip('"')
        #     p = subprocess.Popen(["java","-jar","leshan-client-demo.jar","-n","urn:lo:lwm2m:"+self.connectClient_inputEndPointName.text(),"-i",self.connectClient_inputEndPointName.text(),"-p","1d576207727841a7b9aa2a1f24448f86","-u","lwm2m.integ.m2m.orange.com"], stdin=subprocess.PIPE,stderr=subprocess.PIPE)
        # else:
        #     print("p has already been changed")
        # self.currentDevice_display.setText(self.connectClient_inputEndPointName.text())

        subprocess.Popen(["java","-jar","leshan-client-demo.jar","-n","urn:lo:lwm2m:", "test1","-i", "test1","-p","1d576207727841a7b9aa2a1f24448f86","-u","lwm2m.integ.m2m.orange.com"])
        #subprocess.Popen(["java -jar leshan-client-demo.jar -n urn:lo:lwm2m:test1 -i test1 -p 1d576207727841a7b9aa2a1f24448f86 -u lwm2m.integ.m2m.orange.com"])
        #subprocess.Popen("java -jar leshan-client-demo.jar -n urn:lo:lwm2m:test1 -i test1 -p 1d576207727841a7b9aa2a1f24448f86 -u lwm2m.integ.m2m.orange.com",shell = True)


connectIface_function()
